a = int(input("Ingrese un valor para A\n"))
b = int(input("Ingrese un valor para B\n"))
c = int(input("Ingrese un valor para C\n"))
d = int(input("Ingrese un valor para D\n"))
e = int(input("Ingrese un valor para E\n"))
f = int(input("Ingrese un valor para F\n"))
x = int(((c * e) - (b * f)) / ((a * e) - (b * d)))
y = int(((c * e) - (b * f)) / ((a * e) - (b * d)))
print("El valor de x es: ", x)
print("El valor de y es: ", y)
